language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS=--prefer-lowest
  - COMPOSER_FLAGS=

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer update --no-interaction --no-suggest --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
